### PR TITLE
Simplifying the hasPermission interface by always handling the array …

### PR DESCRIPTION
**Pull request by gpickin**
…of permissions in the abstraction, not the interface.

### CODE REVIEW

**Review by elpete — APPROVED** [review]

**Comment by lmajano** [comment]
If this is the case, then you better update the interface file as well please.

**Review by lmajano — CHANGES_REQUESTED** [review]
Change the interface as well.

**Comment by gpickin** [comment]
Cleaned up the interface.
Made some of the other interfaces consistent, some say 2 keys, some say 3 keys, some have docs for 2 and 3, so made them consistent.

Also, removed the default value of TRUE for secured annotation, so it doesn't send a permission with name of TRUE through to the hasPermission interface unnecessarily.

**Comment by lmajano** [comment]
@gpickin just make sure you update the docs, so I can release the updates

**Pull request merged**
